/* ============================================================================
   Convexity — data layer.
   Talks to the FastAPI backend when the dashboard is served by it, and falls
   back to a bundled sample scan when opened without a backend (demo mode).

   Backend contract (see convexity/api/routes):
     GET  /health                         -> {status:"ok", ...}
     POST /api/scans                      -> 202 {id, status, progress}
     GET  /api/scans/latest               -> {job_id, result} | 404
     GET  /api/scans/{id}                 -> {id, status, progress, has_result}
     GET  /api/scans/{id}/result          -> {job_id, result}
     GET  /api/scans/{id}/events          -> SSE: event: progress|done|error
     GET  /api/companies/{ticker}         -> {ticker, analysis} | analysis
   ========================================================================== */

const API_BASE = "/api";

async function ping() {
  try { const r = await fetch("/health"); return r.ok; } catch (_e) { return false; }
}

let _liveCache = null;
export async function isLive() {
  if (_liveCache === null) _liveCache = await ping();
  return _liveCache;
}

/* Bundled sample scan — works from disk and when served. Returns a ScanResult. */
export async function loadSample() {
  for (const url of ["sample_scan.json", "./sample_scan.json", "examples/sample_scan.json"]) {
    try { const r = await fetch(url); if (r.ok) return await r.json(); } catch (_e) { /* next */ }
  }
  throw new Error("sample scan not found");
}

/* Published REAL scan (a trimmed artifact of an actual engine run, generated by
   scripts/publish_scan.py). Preferred over the illustrative sample when present.
   Returns {scan, kind} where kind is "published" or "sample". */
export async function loadPublished() {
  for (const url of ["latest_scan.json", "./latest_scan.json"]) {
    try {
      const r = await fetch(url);
      if (r.ok) return { scan: await r.json(), kind: "published" };
    } catch (_e) { /* next */ }
  }
  return { scan: await loadSample(), kind: "sample" };
}

/* Most recent completed scan (ScanResult), or null. */
export async function loadLatest() {
  try {
    const r = await fetch(`${API_BASE}/scans/latest`);
    if (!r.ok) return null;
    const data = await r.json();
    return data.result || null;
  } catch (_e) { return null; }
}

/* Start a live scan; stream progress via SSE; resolve with the ScanResult.
   onProgress({stage, done, total, message, pct}). */
export async function runScan(params, onProgress) {
  const id = await startScan(params);
  return await followScan(id, onProgress);
}

/* Start a scan and return its job id (so callers can persist it for reattach).
   The API's canonical body nests the screen under "params" — fields sent flat
   used to be silently ignored, so scans ran on pure defaults. */
export async function startScan(params) {
  const r = await fetch(`${API_BASE}/scans`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ params }),
  });
  if (!r.ok) throw new Error(`scan start failed (${r.status})`);
  const job = await r.json();
  if (!job.id) throw new Error("no scan id returned");
  return job.id;
}

/* Discover in-flight scans (page reload / browser that lost track). */
export async function activeScans() {
  try {
    const r = await fetch(`${API_BASE}/scans/active`);
    if (!r.ok) return [];
    const jobs = await r.json();
    return Array.isArray(jobs) ? jobs : [];
  } catch (_e) { return []; }
}

/* Status of one job: {id, status, progress} or null when unknown. */
export async function scanStatus(id) {
  try {
    const r = await fetch(`${API_BASE}/scans/${id}`);
    if (!r.ok) return null;
    return await r.json();
  } catch (_e) { return null; }
}

async function fetchResult(id) {
  const r = await fetch(`${API_BASE}/scans/${id}/result`);
  if (!r.ok) throw new Error(`result unavailable (${r.status})`);
  const data = await r.json();
  return data.result || data;
}

function pct(p) { return p && p.total ? Math.round((p.done / p.total) * 100) : (p && p.pct) || 0; }

/* Follow a scan until the SERVER says it finished or failed.

   Durability rules (a full-universe scan legitimately runs 30-90+ minutes):
   - NO client-side deadline. The only terminal states are the server reporting
     "completed" or "failed" — a slow scan is a running scan, never a timeout.
   - SSE first; any stream hiccup falls back to polling, and polling retries
     through transient network errors indefinitely.
   - If nothing has been heard for a while the caller gets a heartbeat progress
     callback (stalled: true) so the UI can say "still working" instead of dying. */
export function followScan(id, onProgress) {
  return new Promise((resolve, reject) => {
    let done = false;
    let lastHeard = performance.now();
    const finish = async () => {
      if (done) return; done = true;
      try { resolve(await fetchResult(id)); } catch (e) { reject(e); }
    };
    const fail = (msg) => { if (done) return; done = true; reject(new Error(msg || "scan failed")); };

    // Stall heartbeat: reassure the UI when no event has arrived for 90s.
    const stallTimer = setInterval(() => {
      if (done) { clearInterval(stallTimer); return; }
      const quietFor = (performance.now() - lastHeard) / 1000;
      if (quietFor > 90) {
        onProgress && onProgress({ stalled: true, quiet_seconds: Math.round(quietFor),
          message: `still working — no update for ${Math.round(quietFor)}s (long scans are normal)` });
      }
    }, 30000);
    const heard = () => { lastHeard = performance.now(); };

    const poll = () => {
      const tick = async () => {
        if (done) return;
        const data = await scanStatus(id);
        if (data) {
          heard();
          if (data.progress) onProgress && onProgress({ ...data.progress, pct: pct(data.progress) });
          if (data.status === "completed") { clearInterval(stallTimer); return finish(); }
          if (data.status === "failed") { clearInterval(stallTimer); return fail(data.error || "scan failed"); }
        }
        // Unknown/transient errors: keep polling — the server decides when it's over.
        setTimeout(tick, 1500);
      };
      tick();
    };

    let es;
    try { es = new EventSource(`${API_BASE}/scans/${id}/events`); }
    catch (_e) { return poll(); }

    es.addEventListener("progress", (ev) => {
      heard();
      try { const p = JSON.parse(ev.data); onProgress && onProgress({ ...p, pct: pct(p) }); } catch (_e) {}
    });
    es.addEventListener("done", () => { es.close(); clearInterval(stallTimer); finish(); });
    es.addEventListener("error", (ev) => {
      // A named "error" frame carries data (real failure); a bare connection
      // drop does not — reconnect via polling and keep following.
      if (ev && ev.data) {
        try { const p = JSON.parse(ev.data); es.close(); clearInterval(stallTimer); return fail(p.error); } catch (_e) {}
      }
      es.close();
      if (!done) poll();
    });
  });
}

/* Single-company analysis (live only). */
export async function fetchCompany(ticker) {
  const r = await fetch(`${API_BASE}/companies/${encodeURIComponent(ticker)}`);
  if (!r.ok) throw new Error(`company ${ticker} not found`);
  const data = await r.json();
  return data.analysis || data;
}
