#!/usr/bin/env python3
"""Generate ``examples/sample_scan.json`` — a representative Convexity scan result.

This script makes the project tangible: it produces a single, well-formed
:class:`~convexity.core.models.ScanResult` document on disk that documentation,
the API, and front-ends can render without any network access or credentials.

How it works
------------
1. **Attempt a tiny real scan** — it first tries to run an actual, deliberately
   small offline scan through :class:`convexity.pipeline.ScanPipeline` (a low
   ``universe_limit`` and ``top_n``). If the full stack is importable and any data
   is reachable, the emitted file is genuinely produced by the real pipeline.
2. **Fall back to a clearly-labelled sample** — if *anything* goes wrong (no
   network, missing optional dependencies such as pydantic/typer, an empty result,
   or any other error), it constructs a representative sample by hand: five
   **invented** small-cap companies with full per-category sub-scores and complete
   narratives. Every invented company, and the result itself, is explicitly and
   repeatedly labelled as illustrative sample data so it can never be mistaken for
   real research output.

Honesty
-------
Convexity is a research and screening tool — never a predictor and never advice.
The fallback data is fabricated solely to demonstrate the *shape* of a scan; its
companies do not exist and its numbers carry no market view whatsoever. That
caveat is written into the result's ``notes``, every company's ``thesis``, and the
file is named ``sample_scan.json`` to keep the framing unambiguous.

The script is dependency-light by design: the fallback path builds plain Python
dicts and serialises them with the standard-library :mod:`json`, so it always
writes valid JSON even when neither the network nor the project's optional
dependencies are available. The output is kept well under 200 KB.
"""

from __future__ import annotations

import datetime as _dt
import json
import os
import sys
from typing import Any, Dict, List, Optional

# --------------------------------------------------------------------------- #
# Paths                                                                        #
# --------------------------------------------------------------------------- #
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.dirname(_THIS_DIR)
_EXAMPLES_DIR = os.path.join(_PROJECT_ROOT, "examples")
_OUTPUT_PATH = os.path.join(_EXAMPLES_DIR, "sample_scan.json")

# Ensure the project package is importable when run as a bare script.
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

_SAMPLE_BANNER = (
    "ILLUSTRATIVE SAMPLE DATA — these companies are invented to demonstrate the "
    "shape of a Convexity scan. Convexity is a research & screening tool, not a "
    "predictor and not investment advice. Nothing here reflects a real market view."
)


# --------------------------------------------------------------------------- #
# 1) Try a real, tiny offline scan                                            #
# --------------------------------------------------------------------------- #
def _try_real_scan() -> Optional[Dict[str, Any]]:
    """Attempt a tiny real scan; return its JSON-able dict, or ``None`` on any issue.

    Kept intentionally small (``universe_limit``/``top_n``) so it is quick and
    polite. Any failure — missing dependency, no network, empty result — returns
    ``None`` so the caller falls back to the hand-built sample.
    """
    try:
        from convexity.core.models import ScanParams
        from convexity.pipeline import ScanPipeline

        params = ScanParams(universe_limit=6, top_n=3)
        pipeline = ScanPipeline()
        result = pipeline.scan(params)

        # Only accept a result that actually ranked something; otherwise the
        # hand-built sample is more useful as a representative example.
        if not getattr(result, "all_ranked", None):
            print("[generate_sample] real scan produced no rankings; using sample.")
            return None

        payload = result.model_dump(mode="json")
        # Annotate provenance without altering the genuine data.
        notes = list(payload.get("notes") or [])
        notes.insert(
            0,
            "Generated by an actual Convexity offline scan (small universe_limit). "
            "Research & screening tool — not a predictor and not investment advice.",
        )
        payload["notes"] = notes
        print(f"[generate_sample] real scan succeeded: {len(result.all_ranked)} ranked.")
        return payload
    except Exception as exc:  # noqa: BLE001 - any failure means fall back
        print(f"[generate_sample] real scan unavailable ({exc}); using labelled sample.")
        return None


# --------------------------------------------------------------------------- #
# 2) Hand-built, clearly-labelled representative sample                       #
# --------------------------------------------------------------------------- #
# Eleven additive categories (RISK is a dampener, scored so higher == safer).
_DEFAULT_WEIGHTS: Dict[str, float] = {
    "value": 0.16,
    "growth": 0.15,
    "quality": 0.14,
    "financial_health": 0.13,
    "catalyst": 0.10,
    "competitive": 0.07,
    "management": 0.06,
    "ownership": 0.06,
    "momentum": 0.05,
    "technical": 0.04,
    "historical_analog": 0.04,
    "risk": 0.0,
}


def _evidence(
    label: str,
    value: str,
    source: str,
    direction: str = "neutral",
    detail: Optional[str] = None,
) -> Dict[str, Any]:
    """Build one Evidence dict matching :class:`convexity.core.models.Evidence`."""
    return {
        "label": label,
        "value": value,
        "detail": detail,
        "source": source,
        "as_of": None,
        "url": None,
        "direction": direction,
    }


def _subscore(
    category: str,
    score: float,
    confidence: float,
    weight: float,
    rationale: str,
    evidence: List[Dict[str, Any]],
    flags: Optional[List[str]] = None,
    coverage: float = 0.8,
) -> Dict[str, Any]:
    """Build one SubScore dict matching :class:`convexity.core.models.SubScore`."""
    score = max(0.0, min(100.0, float(score)))
    confidence = max(0.0, min(1.0, float(confidence)))
    coverage = max(0.0, min(1.0, float(coverage)))
    return {
        "category": category,
        "score": score,
        "confidence": confidence,
        "weight": float(weight),
        "rationale": rationale,
        "evidence": evidence,
        "flags": list(flags or []),
        "data_coverage": coverage,
    }


def _full_subscores(profile: Dict[str, float], src: str) -> List[Dict[str, Any]]:
    """Produce a full set of twelve sub-scores from a per-category score profile.

    ``profile`` maps each category string to its 0–100 score; this wraps each into
    a complete SubScore with plausible confidence/coverage, a short rationale and a
    single illustrative Evidence item so the sample mirrors a real analysis shape.
    """
    rationales = {
        "value": "Valuation multiples vs. invented sector peers in this sample.",
        "growth": "Illustrative multi-year revenue and earnings growth trend.",
        "quality": "Sample margins, returns on capital and earnings consistency.",
        "financial_health": "Sample balance-sheet strength, leverage and coverage.",
        "technical": "Illustrative trend and moving-average posture.",
        "momentum": "Sample relative price and earnings-revision momentum.",
        "catalyst": "Invented near-term catalysts (product, contract, filing).",
        "risk": "Sample risk profile (higher score == safer); a dampener, not additive.",
        "management": "Illustrative capital allocation and insider alignment.",
        "competitive": "Sample moat and competitive-position read.",
        "ownership": "Invented institutional and insider ownership signals.",
        "historical_analog": "Sample similarity to past set-ups (illustrative only).",
    }
    units = {
        "value": ("EV/EBITDA", "7.8x", "bullish"),
        "growth": ("3-yr revenue CAGR", "21%", "bullish"),
        "quality": ("Operating margin", "18%", "bullish"),
        "financial_health": ("Net debt / EBITDA", "0.6x", "bullish"),
        "technical": ("Price vs. 200-day MA", "+9%", "bullish"),
        "momentum": ("6-month relative return", "+14%", "bullish"),
        "catalyst": ("Next catalyst", "Q3 product launch", "bullish"),
        "risk": ("Liquidity buffer", "11 months cash", "bullish"),
        "management": ("Insider net buying (12m)", "+$2.1M", "bullish"),
        "competitive": ("Gross-margin stability", "stable", "neutral"),
        "ownership": ("Institutional ownership", "42%", "neutral"),
        "historical_analog": ("Analog cohort hit-rate", "illustrative", "neutral"),
    }
    out: List[Dict[str, Any]] = []
    for category, weight in _DEFAULT_WEIGHTS.items():
        score = float(profile.get(category, 55.0))
        confidence = round(min(0.9, 0.45 + score / 250.0), 3)
        coverage = round(min(0.95, 0.5 + score / 300.0), 3)
        label, value, direction = units[category]
        ev = [_evidence(label, value, src, direction=direction)]
        out.append(
            _subscore(
                category=category,
                score=score,
                confidence=confidence,
                weight=weight,
                rationale="[SAMPLE] " + rationales[category],
                evidence=ev,
                coverage=coverage,
            )
        )
    return out


def _composite(profile: Dict[str, float]) -> float:
    """Approximate the additive composite (weight*score over non-risk categories)."""
    num = 0.0
    den = 0.0
    for category, weight in _DEFAULT_WEIGHTS.items():
        if category == "risk" or weight <= 0:
            continue
        num += weight * float(profile.get(category, 55.0))
        den += weight
    base = num / den if den else 55.0
    # Apply the same RISK dampener shape the real scorer uses.
    risk_norm = float(profile.get("risk", 55.0)) / 100.0
    multiplier = 0.6 + 0.8 * risk_norm if risk_norm < 0.5 else 1.0
    return round(max(0.0, min(100.0, base * multiplier)), 2)


def _company(
    ticker: str,
    name: str,
    sector: str,
    industry: str,
    market_cap: float,
    cap_tier: str,
    profile: Dict[str, float],
    rank: int,
    conviction: float,
    signal_agreement: float,
    thesis: str,
    bull: List[str],
    bear: List[str],
    catalysts: List[str],
    risks: List[str],
    monitoring: List[str],
) -> Dict[str, Any]:
    """Assemble one fully-populated, clearly-labelled sample CompanyAnalysis dict."""
    src = f"SAMPLE:{ticker}"
    return {
        "ticker": ticker,
        "name": name,
        "industry": industry,
        "sector": sector,
        "market_cap": market_cap,
        "cap_tier": cap_tier,
        "composite_score": _composite(profile),
        "conviction_confidence": round(max(0.0, min(1.0, conviction)), 3),
        "rank": rank,
        "subscores": _full_subscores(profile, src),
        "thesis": "[ILLUSTRATIVE SAMPLE — invented company] " + thesis,
        "bull_case": bull,
        "bear_case": bear,
        "catalysts": catalysts,
        "principal_risks": risks,
        "valuation_summary": (
            "[SAMPLE] Trades at an invented mid-single-digit EV/EBITDA, a discount "
            "to its (also invented) peer set."
        ),
        "fundamental_summary": (
            "[SAMPLE] Illustrative double-digit revenue growth with positive free "
            "cash flow and modest leverage."
        ),
        "technical_summary": (
            "[SAMPLE] Price holds above its long-term moving average in this "
            "illustrative series."
        ),
        "confidence_explanation": (
            "[SAMPLE] Confidence reflects how many independent categories agree; "
            "this is fabricated demonstration data, so treat it as shape-only."
        ),
        "monitoring_checklist": monitoring,
        "signal_agreement": round(max(0.0, min(1.0, signal_agreement)), 3),
    }


def _sample_companies() -> List[Dict[str, Any]]:
    """Return five invented sample companies, best-first."""
    companies: List[Dict[str, Any]] = []

    companies.append(
        _company(
            ticker="NVLX",
            name="Novalux Instruments Inc. (SAMPLE)",
            sector="Technology",
            industry="Scientific & Technical Instruments",
            market_cap=410_000_000,
            cap_tier="small",
            profile={
                "value": 78, "growth": 74, "quality": 71, "financial_health": 80,
                "catalyst": 68, "competitive": 66, "management": 72, "ownership": 64,
                "momentum": 70, "technical": 67, "historical_analog": 58, "risk": 74,
            },
            rank=1,
            conviction=0.74,
            signal_agreement=0.81,
            thesis=(
                "A profitable niche instruments maker screening cheap on several "
                "independent measures at once — value, growth and balance-sheet "
                "strength all point the same way in this illustrative case."
            ),
            bull=[
                "[SAMPLE] Cheap on EV/EBITDA and P/FCF versus invented peers.",
                "[SAMPLE] Double-digit revenue growth with expanding margins.",
                "[SAMPLE] Net cash balance sheet funds growth without dilution.",
            ],
            bear=[
                "[SAMPLE] Customer concentration in a few large research labs.",
                "[SAMPLE] Small float can amplify price swings.",
            ],
            catalysts=[
                "[SAMPLE] New product line shipping next quarter.",
                "[SAMPLE] Potential index inclusion on continued growth.",
            ],
            risks=[
                "[SAMPLE] Demand tied to research-funding cycles.",
                "[SAMPLE] Thin liquidity relative to larger peers.",
            ],
            monitoring=[
                "[SAMPLE] Track gross margin trend over the next two prints.",
                "[SAMPLE] Watch order backlog and customer concentration.",
                "[SAMPLE] Confirm free cash flow stays positive.",
            ],
        )
    )

    companies.append(
        _company(
            ticker="HRVS",
            name="Harvest Ridge Agritech Corp. (SAMPLE)",
            sector="Industrials",
            industry="Farm & Heavy Construction Machinery",
            market_cap=265_000_000,
            cap_tier="micro",
            profile={
                "value": 72, "growth": 69, "quality": 64, "financial_health": 70,
                "catalyst": 71, "competitive": 60, "management": 66, "ownership": 68,
                "momentum": 63, "technical": 61, "historical_analog": 55, "risk": 66,
            },
            rank=2,
            conviction=0.66,
            signal_agreement=0.7,
            thesis=(
                "An illustrative micro-cap equipment maker with a credible order "
                "pipeline and insider buying, screening reasonably across the "
                "fundamental categories."
            ),
            bull=[
                "[SAMPLE] Backlog up sharply on new dealer agreements.",
                "[SAMPLE] Insiders have been net buyers over the past year.",
            ],
            bear=[
                "[SAMPLE] Cyclical end-markets sensitive to commodity prices.",
                "[SAMPLE] Moderate leverage limits downside cushion.",
            ],
            catalysts=[
                "[SAMPLE] Large fleet order expected to close this half.",
                "[SAMPLE] Margin step-up from a new factory line.",
            ],
            risks=[
                "[SAMPLE] Input-cost inflation could compress margins.",
                "[SAMPLE] Weather/season swings affect quarterly demand.",
            ],
            monitoring=[
                "[SAMPLE] Watch backlog conversion to revenue.",
                "[SAMPLE] Monitor net debt / EBITDA each quarter.",
            ],
        )
    )

    companies.append(
        _company(
            ticker="MDBR",
            name="Meridian Biopharma Ltd. (SAMPLE)",
            sector="Healthcare",
            industry="Biotechnology",
            market_cap=180_000_000,
            cap_tier="micro",
            profile={
                "value": 55, "growth": 80, "quality": 50, "financial_health": 58,
                "catalyst": 84, "competitive": 62, "management": 60, "ownership": 70,
                "momentum": 72, "technical": 64, "historical_analog": 52, "risk": 44,
            },
            rank=3,
            conviction=0.52,
            signal_agreement=0.55,
            thesis=(
                "A higher-variance illustrative biotech: strong catalyst and growth "
                "reads offset by a weaker risk score, so conviction stays modest "
                "despite some bullish categories."
            ),
            bull=[
                "[SAMPLE] Phase-2 readout due within months.",
                "[SAMPLE] Cash runway covers the next two catalysts.",
            ],
            bear=[
                "[SAMPLE] Binary clinical outcome dominates the thesis.",
                "[SAMPLE] No product revenue yet; pre-commercial.",
            ],
            catalysts=[
                "[SAMPLE] Top-line Phase-2 data expected next quarter.",
                "[SAMPLE] Potential partnership announcement.",
            ],
            risks=[
                "[SAMPLE] Trial failure would impair value materially.",
                "[SAMPLE] Future financing could dilute holders.",
            ],
            monitoring=[
                "[SAMPLE] Track cash runway against catalyst timing.",
                "[SAMPLE] Watch for trial-enrollment updates.",
                "[SAMPLE] Note any going-concern language in filings.",
            ],
        )
    )

    companies.append(
        _company(
            ticker="CSTL",
            name="Coastal Logistics Group (SAMPLE)",
            sector="Industrials",
            industry="Integrated Freight & Logistics",
            market_cap=520_000_000,
            cap_tier="small",
            profile={
                "value": 66, "growth": 58, "quality": 68, "financial_health": 72,
                "catalyst": 54, "competitive": 64, "management": 70, "ownership": 60,
                "momentum": 56, "technical": 59, "historical_analog": 57, "risk": 70,
            },
            rank=4,
            conviction=0.6,
            signal_agreement=0.62,
            thesis=(
                "A steadier illustrative logistics operator: solid quality and "
                "financial-health reads, fewer near-term catalysts, lower variance."
            ),
            bull=[
                "[SAMPLE] Consistent free cash flow and disciplined capital returns.",
                "[SAMPLE] Regional density gives a modest cost edge.",
            ],
            bear=[
                "[SAMPLE] Freight rates are cyclical and can soften quickly.",
                "[SAMPLE] Limited growth catalysts in the near term.",
            ],
            catalysts=[
                "[SAMPLE] Potential tuck-in acquisition of a regional carrier.",
                "[SAMPLE] Buyback program could resume.",
            ],
            risks=[
                "[SAMPLE] Fuel-cost swings affect margins.",
                "[SAMPLE] Exposure to a single large shipper.",
            ],
            monitoring=[
                "[SAMPLE] Watch operating ratio quarter over quarter.",
                "[SAMPLE] Track free cash flow conversion.",
            ],
        )
    )

    companies.append(
        _company(
            ticker="TERN",
            name="Tern Specialty Materials (SAMPLE)",
            sector="Materials",
            industry="Specialty Chemicals",
            market_cap=340_000_000,
            cap_tier="small",
            profile={
                "value": 70, "growth": 60, "quality": 62, "financial_health": 65,
                "catalyst": 58, "competitive": 68, "management": 63, "ownership": 59,
                "momentum": 55, "technical": 57, "historical_analog": 54, "risk": 64,
            },
            rank=5,
            conviction=0.57,
            signal_agreement=0.6,
            thesis=(
                "An illustrative specialty-materials maker screening cheap with a "
                "defensible niche; signals are constructive but not unanimous."
            ),
            bull=[
                "[SAMPLE] Proprietary formulations support pricing power.",
                "[SAMPLE] Valuation discount to invented specialty-chem peers.",
            ],
            bear=[
                "[SAMPLE] Raw-material cost pass-through can lag.",
                "[SAMPLE] Moderate customer concentration.",
            ],
            catalysts=[
                "[SAMPLE] New high-margin product qualification underway.",
                "[SAMPLE] Capacity expansion completing this year.",
            ],
            risks=[
                "[SAMPLE] Input-cost volatility.",
                "[SAMPLE] Regulatory changes affecting chemical handling.",
            ],
            monitoring=[
                "[SAMPLE] Track gross margin versus input costs.",
                "[SAMPLE] Watch new-product qualification milestones.",
            ],
        )
    )

    return companies


def _build_sample_result() -> Dict[str, Any]:
    """Construct the full, clearly-labelled sample :class:`ScanResult` as a dict."""
    companies = _sample_companies()
    now = _dt.datetime.now(_dt.timezone.utc).isoformat()

    params = {
        "min_market_cap": 50_000_000.0,
        "max_market_cap": 2_000_000_000.0,
        "min_avg_dollar_volume": 200_000.0,
        "exclude_sectors": [],
        "top_n": 5,
        "universe_limit": 25,
    }

    notes = [
        _SAMPLE_BANNER,
        "This file was produced by scripts/generate_sample.py as a fallback because "
        "a live offline scan was unavailable in the generating environment.",
        "All five companies are fictional; tickers, names and every number are "
        "fabricated to illustrate the structure of a Convexity scan only.",
        "Convexity surfaces names where many INDEPENDENT signals agree — it is a "
        "research & screening aid, never a predictor and never investment advice.",
        f"Sample scan: 25 candidate(s) screened, {len(companies)} analysed, "
        "0 fetch error(s) (illustrative).",
    ]

    return {
        "generated_at": now,
        "params": params,
        "universe_size": 25,
        "screened_count": len(companies),
        "analyzed_count": len(companies),
        "error_count": 0,
        "top": companies,
        "all_ranked": companies,
        "category_weights": dict(_DEFAULT_WEIGHTS),
        "elapsed_seconds": 0.42,
        "notes": notes,
    }


# --------------------------------------------------------------------------- #
# Entry point                                                                  #
# --------------------------------------------------------------------------- #
def main() -> int:
    """Generate the sample, write it to ``examples/sample_scan.json``, return a code."""
    os.makedirs(_EXAMPLES_DIR, exist_ok=True)

    payload = _try_real_scan()
    if payload is None:
        payload = _build_sample_result()

    text = json.dumps(payload, indent=2, ensure_ascii=False, default=str)

    # Keep the artefact comfortably small.
    size = len(text.encode("utf-8"))
    if size > 200_000:  # pragma: no cover - sample is intentionally compact
        print(f"[generate_sample] WARNING: output is {size} bytes (>200KB target).")

    with open(_OUTPUT_PATH, "w", encoding="utf-8") as fh:
        fh.write(text)
        fh.write("\n")

    print(f"[generate_sample] wrote {_OUTPUT_PATH} ({size} bytes).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
